services:
  - type: web
    name: Barberia-Plus
    env: PHP
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan migrate --force
      php artisan db:seed --force
      npm install && npm run build
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
